name: csgenv
dependencies:
  - python=3.6.7
  - pip
  - rdkit
  - pip:
    - Theano==1.0.3
    - numpy==1.16.4
    - scipy==1.3.0
    - torch==1.1.0
    - sklearn==0.0
    - deepchem==2.1.1.dev353
    - torch-scatter==1.2.0
    - torch-sparse==0.4.0
    - torch-cluster==1.4.2
    - torch-geometric==1.2.1
    - torch-spline-conv==1.1.0
    - torchvision==0.3.0
    - pickle>=0.7.5
